"""Anonymized market legends and a factual historical timeline.

Legend characters are fictionalized archetypes inspired by real market
folklore. Names are deliberately omitted; each dossier carries a factual
footnote about the era instead.
"""

LEGEND_STAMP = {"zh": "传说档案", "en": "LEGEND DOSSIER"}

LEGENDS = [
    {
        "id": "lg01",
        "file_no": "LG-2000-001",
        "tag_zh": "游资传说",
        "tag_en": "Hot money legend",
        "era_zh": "2000 年代 · 涨停敢死队",
        "era_en": "2000s · The Limit-Up Commandos",
        "source_zh": "营业部传闻",
        "source_en": "brokerage floor lore",
        "title_zh": "甬城敢死队队长",
        "title_en": "The Commander of the Ningbo Commandos",
        "body_zh": "他一生只做一件事：今天涨停，明天也要涨停。他不看基本面，只看盘口里那口气。后来那口气散了，他在访谈里说：我不是股神，我只是比别人早三秒。",
        "body_en": "He did one thing his whole life: today a limit-up, tomorrow another. He never read fundamentals, only the breath in the order book. When that breath finally left, he said in an interview: I am not a stock god, I was just three seconds earlier than everyone else.",
        "footnote_zh": "2000 年代初，宁波解放南路营业部的短线席位以敢死队式打板闻名，成为一代游资传奇。",
        "footnote_en": "In the early 2000s, short-term seats at a famous Ningbo brokerage branch became known for commando-style limit-up trading, a legend of the era's hot money.",
    },
    {
        "id": "lg02",
        "file_no": "LG-2011-002",
        "tag_zh": "悲情叙事",
        "tag_en": "Tragic narrative",
        "era_zh": "2011 · 关灯吃面",
        "era_en": "2011 · Lights Off, Noodles On",
        "source_zh": "深夜论坛帖",
        "source_en": "a late-night forum post",
        "title_zh": "关灯吃面的男人",
        "title_en": "The Man Who Ate Noodles in the Dark",
        "body_zh": "那晚他没有开灯。一碗面，一碟花生，屏幕绿油油。他说：吃面，不哭，明天还会跌。后来这句话成了散户之间心照不宣的接头暗号。",
        "body_en": "He did not turn on the light that night. A bowl of noodles, a plate of peanuts, and a screen glowing green. He said: eat the noodles, don't cry, tomorrow it falls again. That sentence later became an unspoken password among retail investors.",
        "footnote_zh": "2011 年末，重庆啤酒乙肝疫苗项目宣告失败，股价连续跌停，“关灯吃面”自此成为 A 股悲情叙事的符号。",
        "footnote_en": "In late 2011, a beer maker's hepatitis B vaccine project failed and its stock hit repeated limit-downs; \"lights off, noodles on\" became a symbol of A-share retail tragedy.",
    },
    {
        "id": "lg03",
        "file_no": "LG-2021-003",
        "tag_zh": "财富意象",
        "tag_en": "Wealth imagery",
        "era_zh": "2021 · 锂矿时代",
        "era_en": "2021 · The Lithium Era",
        "source_zh": "矿圈段子",
        "source_en": "mining-camp jokes",
        "title_zh": "麻袋装钱的矿工",
        "title_en": "The Miner with a Sack of Cash",
        "body_zh": "矿工不挖煤，改挖锂。他们说：锂矿里流出来的不是电解质，是麻袋装的钱。他背着一麻袋现金去开户，行情给了他三个月的微笑，然后把麻袋原封不动还给了他。",
        "body_en": "The miner stopped digging coal and started digging lithium. They said what flows out of lithium isn't electrolyte, it's sackfuls of cash. He opened an account carrying one such sack; the market smiled for three months, then handed the sack back untouched.",
        "footnote_zh": "2021 年新能源产业链行情中，锂矿股大幅上涨，“麻袋装钱”成为市场流传的财富意象。",
        "footnote_en": "During the 2021 new-energy rally, lithium miners surged and \"sacks of cash\" became the era's favorite image of sudden wealth.",
    },
    {
        "id": "lg04",
        "file_no": "LG-2004-004",
        "tag_zh": "庄家往事",
        "tag_en": "Market maker lore",
        "era_zh": "2000 年代 · 坐庄时代",
        "era_en": "2000s · The Manipulation Era",
        "source_zh": "庭审旁听记录",
        "source_en": "courtroom notes",
        "title_zh": "白手套庄家",
        "title_en": "The White-Glove Manipulator",
        "body_zh": "他从不自己持股，账户都在别人名下。拉高出货前，他会在饭局上喝三杯酒，说一句：这支票，有故事。后来故事讲完了，他也进去了。",
        "body_en": "He never held shares in his own name; every account belonged to someone else. Before the final mark-up, he would drink three toasts at dinner and say: this stock has a story. When the story ended, so did his freedom.",
        "footnote_zh": "2000 年代，联合坐庄与账户代持现象时有发生，此后监管持续收紧，多位知名庄家相继被查处。",
        "footnote_en": "In the 2000s, coordinated manipulation and nominee accounts were common; regulators later tightened enforcement and prosecuted several famous manipulators.",
    },
    {
        "id": "lg05",
        "file_no": "LG-2015-005",
        "tag_zh": "杠杆时代",
        "tag_en": "The leverage age",
        "era_zh": "2015 · 配资牛市",
        "era_en": "2015 · The Margin Bull",
        "source_zh": "强平短信",
        "source_en": "a forced-liquidation alert",
        "title_zh": "配资狂人",
        "title_en": "The Margin Fanatic",
        "body_zh": "十倍的勇气，十天的牛市。他把配资比例背得像股票代码一样熟：10，20，50。最后三天，他学会了一个新词：强平。",
        "body_en": "Ten times the courage, ten days of bull market. He recited leverage ratios like tickers: 10, 20, 50. In the final three days he learned a new word: forced liquidation.",
        "footnote_zh": "2015 年上半年场外配资快速膨胀，下半年去杠杆引发剧烈调整，千股跌停成为那一年的集体记忆。",
        "footnote_en": "Off-exchange margin financing ballooned in the first half of 2015; deleveraging then triggered a brutal correction and days of a thousand limit-downs.",
    },
    {
        "id": "lg06",
        "file_no": "LG-2015-006",
        "tag_zh": "全民开户",
        "tag_en": "A nation of accounts",
        "era_zh": "2015 · 跑步入场",
        "era_en": "2015 · Running In",
        "source_zh": "营业部门口",
        "source_en": "outside a brokerage branch",
        "title_zh": "穿睡衣的大妈",
        "title_en": "The Grandma in Pajamas",
        "body_zh": "她早上六点排队开户，穿着睡衣，手里攥着买菜钱。营业部经理问她有什么投资经验，她说：菜市场天天涨价，股票还能差到哪去？",
        "body_en": "She queued to open an account at six in the morning, still in pajamas, clutching the grocery money. When the manager asked about her experience, she said: if the vegetable market rises every day, how bad can stocks be?",
        "footnote_zh": "2015 年牛市期间新开户数激增，全民炒股的景象让“跑步入场”成为年度热词。",
        "footnote_en": "New accounts surged during the 2015 bull run, and \"running into the market\" became the phrase of the year.",
    },
    {
        "id": "lg07",
        "file_no": "LG-1989-007",
        "tag_zh": "第一代套利者",
        "tag_en": "First-generation arbitrage",
        "era_zh": "1989 · 国库券年代",
        "era_en": "1989 · The Treasury Bond Years",
        "source_zh": "绿皮火车车厢",
        "source_en": "a green hard-seat train",
        "title_zh": "国债倒爷",
        "title_en": "The Bond Runner",
        "body_zh": "他坐一夜绿皮火车，从一座城市倒国库券到另一座城市，赚的是两张报纸之间的价差。后来交易所开业，他改行了，说：这行当太慢。",
        "body_en": "He rode green hard-seat trains overnight, moving treasury bonds between cities to capture price differences that only two newspapers could reveal. When the exchange opened he switched careers: too slow, he said.",
        "footnote_zh": "1980 年代末国库券允许流通后，异地价差催生了中国第一批职业证券套利者。",
        "footnote_en": "Once treasury bonds became tradable in the late 1980s, cross-city price gaps created China's first professional securities arbitrageurs.",
    },
    {
        "id": "lg08",
        "file_no": "LG-2016-008",
        "tag_zh": "机制实验",
        "tag_en": "An experiment in rules",
        "era_zh": "2016 · 熔断四日游",
        "era_en": "2016 · Four Days of Circuit Breakers",
        "source_zh": "年假申请单",
        "source_en": "a vacation request form",
        "title_zh": "熔断四日游",
        "title_en": "Four Days of Circuit Breakers",
        "body_zh": "他请了年假准备迎接新年行情，结果开盘四天，熔断两次，假期直接延长到退休。他总结：机制是新的，教训是老的。",
        "body_en": "He took annual leave for the new-year rally. Four sessions later the market had tripped circuit breakers twice and his vacation extended into retirement. His verdict: the mechanism was new, the lesson old.",
        "footnote_zh": "2016 年元旦后 A 股引入熔断机制，四个交易日内两次触发，随后该机制被暂停。",
        "footnote_en": "Circuit breakers arrived after New Year 2016 and tripped twice within four sessions before being suspended.",
    },
    {
        "id": "lg09",
        "file_no": "LG-2001-009",
        "tag_zh": "神话破灭",
        "tag_en": "The myth collapses",
        "era_zh": "2001 · 西部神话",
        "era_en": "2001 · The Western Miracle",
        "source_zh": "年报复核记录",
        "source_en": "an annual report audit trail",
        "title_zh": "西部神话股的持有人",
        "title_en": "The Holder of the Western Miracle",
        "body_zh": "每股三元的业绩神话，听上去像戈壁滩上的绿洲。后来绿洲被证实是海市蜃楼，他的账户和业绩一起归零。他说：神话里最值钱的，是退场券。",
        "body_en": "Three yuan per share of miracle earnings sounded like an oasis in the desert. The oasis turned out to be a mirage, and his account zeroed out with the earnings. He said: the most valuable thing in a myth is the exit ticket.",
        "footnote_zh": "2001 年，某西部上市公司财务造假曝光，股价连续跌停，成为 A 股早期重大造假案例之一。",
        "footnote_en": "In 2001, a western-listed company's accounting fraud was exposed, its shares hit consecutive limit-downs, and it became one of A-shares' early landmark fraud cases.",
    },
    {
        "id": "lg10",
        "file_no": "LG-1992-010",
        "tag_zh": "认购证时代",
        "tag_en": "The certificate era",
        "era_zh": "1992 · 认购证长队",
        "era_en": "1992 · The Certificate Queue",
        "source_zh": "排队者口述",
        "source_en": "oral accounts from the queue",
        "title_zh": "认购证长队的排头兵",
        "title_en": "The First in the Certificate Line",
        "body_zh": "他排了三个通宵，买到三十张认购证，像捧着一沓还没开奖的彩票。后来奖开了，他把那一晚排队的经历讲了一辈子。",
        "body_en": "He queued three nights for thirty subscription certificates, holding them like unopened lottery tickets. When the lottery opened, he told the story of that night for the rest of his life.",
        "footnote_zh": "1992 年上海发行股票认购证，申购队伍蜿蜒数公里，“认购证造富”成为那一代人的集体记忆。",
        "footnote_en": "In 1992, Shanghai issued stock subscription certificates and queues stretched for kilometers; certificate wealth became a generation's shared memory.",
    },
]

TIMELINE = [
    {
        "year": "1988",
        "title_zh": "国库券流通试点",
        "title_en": "Treasury Bond Trading Pilot",
        "fact_zh": "国库券允许上市流通，异地价差催生了中国第一批证券套利者。",
        "fact_en": "Treasury bonds became tradable, and cross-city price gaps created China's first securities arbitrageurs.",
    },
    {
        "year": "1990",
        "title_zh": "上交所开业",
        "title_en": "The Shanghai Exchange Opens",
        "fact_zh": "上海证券交易所正式开业，首批八只股票挂牌，史称“老八股”。",
        "fact_en": "The Shanghai Stock Exchange opens with eight listed stocks, later known as the \"old eight.\"",
    },
    {
        "year": "1992",
        "title_zh": "认购证发行",
        "title_en": "Subscription Certificates",
        "fact_zh": "上海股票认购证发行，万人排队申购，成为早期市场最著名的事件之一。",
        "fact_en": "Stock subscription certificates go on sale in Shanghai; queues stretch for kilometers in one of the market's most famous early events.",
    },
    {
        "year": "1996",
        "title_zh": "涨跌停制度",
        "title_en": "Price Limits Introduced",
        "fact_zh": "沪深交易所全面实施 10% 涨跌幅限制，这一规则沿用至今。",
        "fact_en": "Both exchanges introduce the 10% daily price limit, a rule that still defines the market.",
    },
    {
        "year": "1999",
        "title_zh": "5·19 行情",
        "title_en": "The May 19 Rally",
        "fact_zh": "网络科技股带动大盘放量大涨，两年后沪指触及 2245 点。",
        "fact_en": "Internet and tech names ignite a volume-driven rally; two years later the index reaches 2,245 points.",
    },
    {
        "year": "2001",
        "title_zh": "国有股减持与造假案",
        "title_en": "State-Share Reduction and a Fraud Case",
        "fact_zh": "国有股减持方案引发市场调整；同年银广夏财务造假案曝光。",
        "fact_en": "A state-share reduction plan triggers a sell-off; the same year, a landmark accounting fraud at a listed company is exposed.",
    },
    {
        "year": "2005",
        "title_zh": "股权分置改革",
        "title_en": "Split-Share Reform",
        "fact_zh": "股权分置改革启动，被广泛视为随后一轮大牛市的制度基础。",
        "fact_en": "Split-share reform begins and is widely credited as the institutional foundation of the bull market to come.",
    },
    {
        "year": "2007",
        "title_zh": "6124 点",
        "title_en": "The 6,124 Peak",
        "fact_zh": "上证指数触及历史高点 6124.04 点，全民炒股达到顶峰。",
        "fact_en": "The Shanghai Composite peaks at 6,124.04, and nationwide retail enthusiasm reaches its high-water mark.",
    },
    {
        "year": "2008",
        "title_zh": "全球金融危机",
        "title_en": "The Global Financial Crisis",
        "fact_zh": "金融危机冲击 A 股，沪指从 6124 点回落至 1664 点。",
        "fact_en": "The financial crisis hits A-shares, dragging the index from 6,124 down to 1,664.",
    },
    {
        "year": "2010",
        "title_zh": "股指期货上市",
        "title_en": "Stock Index Futures",
        "fact_zh": "沪深 300 股指期货上市，A 股进入可以做空的时代。",
        "fact_en": "CSI 300 index futures launch, giving A-shares a shorting tool for the first time.",
    },
    {
        "year": "2015",
        "title_zh": "千股跌停",
        "title_en": "A Thousand Limit-Downs",
        "fact_zh": "杠杆牛市见顶后市场剧烈调整，多日出现千股跌停。",
        "fact_en": "After the leveraged bull peaks, the market corrects violently and a thousand stocks hit limit-down on several days.",
    },
    {
        "year": "2019",
        "title_zh": "科创板开市",
        "title_en": "The STAR Market Opens",
        "fact_zh": "科创板正式开市，注册制试点落地，A 股开启新的市场结构。",
        "fact_en": "The STAR Market opens with a registration-based listing pilot, reshaping the A-share market structure.",
    },
]


def localize_legend(legend: dict, lang: str) -> dict:
    zh = lang == "zh"
    return {
        "id": legend["id"],
        "file_no": legend["file_no"],
        "tag": legend["tag_zh"] if zh else legend["tag_en"],
        "era": legend["era_zh"] if zh else legend["era_en"],
        "source": legend["source_zh"] if zh else legend["source_en"],
        "stamp": LEGEND_STAMP["zh" if zh else "en"],
        "title": legend["title_zh"] if zh else legend["title_en"],
        "story": legend["body_zh"] if zh else legend["body_en"],
        "footnote": legend["footnote_zh"] if zh else legend["footnote_en"],
    }


def localize_event(event: dict, lang: str) -> dict:
    zh = lang == "zh"
    return {
        "year": event["year"],
        "title": event["title_zh"] if zh else event["title_en"],
        "fact": event["fact_zh"] if zh else event["fact_en"],
    }
