"""Fun fictional retail investor stories shown to the player."""

STORIES = [
    {
        "id": "s01",
        "tag_zh": "听消息",
        "tag_en": "Hot tip",
        "title_zh": "七大姑的独家内幕",
        "title_en": "Auntie's Insider Info",
        "body_zh": "老李的七大姑从牌友那里听说某股票要重组，他连夜满仓。第二天公司发公告说“近期无重大事项”，老李说：消息没错，是行情没听懂。",
        "body_en": "Li's aunt heard from a mahjong partner that a stock was about to restructure, so he went all in overnight. The next day the company announced \"no major events.\" Li says the tip was right, the market just didn't understand it.",
    },
    {
        "id": "s02",
        "tag_zh": "抄底",
        "tag_en": "Catching the knife",
        "title_zh": "战略建仓",
        "title_en": "Strategic Positioning",
        "body_zh": "小王坚信“跌多了就是送钱”，每跌 5% 加一次仓。连加十次后，他把这叫做“战略建仓”，而他的持仓成本线已经比海拔还高了。",
        "body_en": "Wang believes every drop is free money and adds shares after each 5% decline. After ten adds he calls it \"strategic positioning,\" and his average cost is now higher than Mount Everest.",
    },
    {
        "id": "s03",
        "tag_zh": "死扛",
        "tag_en": "Diamond hands",
        "title_zh": "回本就走",
        "title_en": "Sell When I Break Even",
        "body_zh": "张姐买了只股票套了三年，她的止损规则是“等回本就卖”。三年后股价真的回本了，她说：涨这么猛，先不卖了，等翻倍。",
        "body_en": "Zhang has held a stock underwater for three years; her stop-loss rule is \"sell when I break even.\" When the price finally recovered, she said it was climbing too fast to sell, so she would wait for it to double.",
    },
    {
        "id": "s04",
        "tag_zh": "卖飞",
        "tag_en": "Sold too soon",
        "title_zh": "我曾买过",
        "title_en": "I Used to Own It",
        "body_zh": "刘叔买完第二天涨了 2% 就跑了，美滋滋。结果那只股票一年涨了 6 倍，现在“我曾经买过”这句话已经写进了他的家族史。",
        "body_en": "Uncle Liu sold after a 2% gain and felt great. The stock went up 6x that year, and \"I used to own it\" has since become part of his family history.",
    },
    {
        "id": "s05",
        "tag_zh": "杠杆",
        "tag_en": "Leverage",
        "title_zh": "牛市靠胆量",
        "title_en": "Bull Markets Reward Courage",
        "body_zh": "小赵开了 5 倍杠杆，一天赚了 15%，他兴奋地发朋友圈“牛市靠胆量”。第二天亏了 20%，他的朋友圈更新成了“市场有风险”。",
        "body_en": "Zhao used 5x leverage and made 15% in one day, posting \"bull markets reward courage.\" The next day he lost 20% and reposted: \"markets are risky.\"",
    },
    {
        "id": "s06",
        "tag_zh": "玄学",
        "tag_en": "Fortune telling",
        "title_zh": "招财猫形态",
        "title_en": "The Lucky Cat Pattern",
        "body_zh": "陈叔选股不看财报，只看手机尾号和 K 线形状。他说那根 W 底长得像他家的招财猫，于是果断买进，并给它取名“招财底”。",
        "body_en": "Chen picks stocks by the last digits of his phone number and the shapes on his chart. He saw a W bottom that looked like his lucky cat, bought in, and named it the \"lucky cat pattern.\"",
    },
    {
        "id": "s07",
        "tag_zh": "电梯内幕",
        "tag_en": "Elevator insider",
        "title_zh": "电梯里的两个西装男",
        "title_en": "Two Guys in Suits",
        "body_zh": "小吴在电梯里听到两个西装男在聊某只股票，当场下单。后来才知道，那两个人是另一家公司的销售，在聊客户名字。",
        "body_en": "Wu bought a stock because he overheard two men in suits discussing it in the elevator. It turned out they were salesmen from another company, talking about a client's name.",
    },
    {
        "id": "s08",
        "tag_zh": "满仓",
        "tag_en": "All in",
        "title_zh": "全家总动员",
        "title_en": "Family Mobilization",
        "body_zh": "老周把买菜钱、孩子压岁钱和备用金都转进了账户，称之为“全家总动员”。月底账户缩水，他称之为“全家福”。",
        "body_en": "Zhou moved the grocery money, the kids' red envelopes, and the emergency fund into trading, calling it \"family mobilization.\" When the account shrank at month end, he called it \"a family portrait.\"",
    },
    {
        "id": "s09",
        "tag_zh": "割肉",
        "tag_en": "Cut losses",
        "title_zh": "我一卖它就涨",
        "title_en": "It Rallies the Moment I Sell",
        "body_zh": "小孙刚割完肉，股票立刻涨停。他总结出新规律：只要我卖，它必涨。现在他成了小区公认的反向指标。",
        "body_en": "Sun sold at a loss and the stock hit the daily limit instantly. He discovered a rule: whenever he sells, it rallies. He is now the neighborhood's official reverse indicator.",
    },
    {
        "id": "s10",
        "tag_zh": "回本",
        "tag_en": "Break even",
        "title_zh": "再赚五万就收手",
        "title_en": "Fifty Thousand More and I Quit",
        "body_zh": "马姐的账户从 20 万亏到 8 万，她每天祈祷“回本就好”。等她真的回本那天，她决定“再赚 5 万就收手”，然后开始了新一轮祈祷。",
        "body_en": "Ma's account fell from 200k to 80k and she prayed daily just to break even. The day she finally did, she decided to \"make 50k more and quit,\" starting a whole new round of praying.",
    },
    {
        "id": "s11",
        "tag_zh": "借钱",
        "tag_en": "Borrowed money",
        "title_zh": "等风来",
        "title_en": "Waiting for the Wind",
        "body_zh": "小郑找亲戚借了 10 万“短期周转”，亲戚问多久，他说“等风来”。三个月后亲戚再问，他说“风还在路上”。",
        "body_en": "Zheng borrowed 100k from relatives for \"short-term liquidity.\" Asked how long, he said \"until the wind comes.\" Three months later they asked again; the wind was still on its way.",
    },
    {
        "id": "s12",
        "tag_zh": "装死",
        "tag_en": "Playing dead",
        "title_zh": "我装作没买过",
        "title_en": "Pretending to Own Nothing",
        "body_zh": "阿强被套后养成了新习惯：每天打开软件只看一眼就关，装作自己没买过。直到某天误触卖出键，他才想起自己还有持仓。",
        "body_en": "After getting trapped, Qiang got into the habit of opening his app, glancing at it, and closing it, pretending he owned nothing. One day he accidentally hit sell and remembered he had positions.",
    },
    {
        "id": "s13",
        "tag_zh": "直播炒股",
        "tag_en": "Live trading",
        "title_zh": "321 上车",
        "title_en": "3, 2, 1, Get In",
        "body_zh": "小丽跟着某财经主播“321 上车”追了一只票，买完主播就下播了。她后来发现主播的简介写着：本节目仅供娱乐。",
        "body_en": "Li chased a stock with a streamer shouting \"3, 2, 1, get in!\", and the streamer went offline right after she bought. She later noticed the bio: \"For entertainment only.\"",
    },
    {
        "id": "s14",
        "tag_zh": "一夜暴富",
        "tag_en": "Get rich quick",
        "title_zh": "大不了重新上班",
        "title_en": "Worst Case, I Go Back to Work",
        "body_zh": "老钱把退休金押进去赌“百年大行情”，他说“大不了重新上班”。后来他真的重新上班了，工牌上写着“夜班保安”。",
        "body_en": "Qian put his pension into a \"once-in-a-century rally,\" saying \"worst case, I go back to work.\" He did. His badge now reads \"night security guard.\"",
    },
    {
        "id": "s15",
        "tag_zh": "反向操作",
        "tag_en": "Contrarian",
        "title_zh": "负负得正",
        "title_en": "Two Negatives Make a Positive",
        "body_zh": "小何发现自己看好的股票都跌、看不上的都涨，于是决定反着买。结果两只一起跌，他说：我这叫负负得正。",
        "body_en": "He noticed that stocks he liked fell and stocks he disliked rallied, so he bought the ones he disliked. Both fell together. His explanation: two negatives make a positive.",
    },
    {
        "id": "s16",
        "tag_zh": "情绪管理",
        "tag_en": "Emotional trading",
        "title_zh": "盘感依赖症",
        "title_en": "Chart Obsession Disorder",
        "body_zh": "老韩每次亏钱就喝酒，喝完就加仓，加完就后悔，后悔就睡不着，睡不着就再看盘。医生说他得了“盘感依赖症”。",
        "body_en": "Han drinks after every loss, adds shares after drinking, regrets it, can't sleep, and checks the charts again. His doctor calls it \"chart-obsession disorder.\"",
    },
    {
        "id": "s17",
        "tag_zh": "开盘前",
        "tag_en": "Before the bell",
        "title_zh": "战歌选错了",
        "title_en": "Wrong Battle Anthems",
        "body_zh": "小杨每天开盘前都要听三首战歌，说这样“气势如虹”。结果开盘十分钟账户就绿了，他说战歌选错了，明天换一首。",
        "body_en": "Yang plays three battle anthems before every open to \"boost morale.\" His account turns green within ten minutes, so he swears he picked the wrong songs and will swap them tomorrow.",
    },
    {
        "id": "s18",
        "tag_zh": "股神附体",
        "tag_en": "Stock god",
        "title_zh": "巴菲特转世",
        "title_en": "Reborn as Buffett",
        "body_zh": "阿杰连续三天猜对涨跌，觉得自己是巴菲特转世，宣布辞职专职炒股。第一周结束，他开始研究外卖骑手的入职流程。",
        "body_en": "Jay predicted three days of moves correctly, declared himself the reincarnation of Buffett, and quit his job to trade full time. By the end of week one he was researching delivery driver applications.",
    },
    {
        "id": "s19",
        "tag_zh": "股吧大师",
        "tag_en": "Forum guru",
        "title_zh": "战术性撤退",
        "title_en": "A Tactical Retreat",
        "body_zh": "老牛白天在群里发“耐心持有，价值投资”，晚上偷偷挂单割肉。群友发现后，他解释：这叫战术性撤退。",
        "body_en": "Niu preaches \"patience and value investing\" in the group chat by day, then quietly sells at a loss at night. When caught, he calls it a tactical retreat.",
    },
    {
        "id": "s20",
        "tag_zh": "目标价",
        "tag_en": "Target price",
        "title_zh": "四舍五入再等等",
        "title_en": "Rounding Up",
        "body_zh": "小美买股票前设好目标价“赚 30% 就卖”。股票涨到 28% 时她犹豫了，四舍五入一下，决定再等等。后来她的目标价改成了“回本就走”。",
        "body_en": "Mei sets a 30% target before buying. At 28% she hesitates, rounds up, and waits a little longer. Her target eventually becomes \"sell when I break even.\"",
    },
]


def localize_story(story: dict, lang: str) -> dict:
    zh = lang == "zh"
    return {
        "id": story["id"],
        "tag": story["tag_zh"] if zh else story["tag_en"],
        "title": story["title_zh"] if zh else story["title_en"],
        "story": story["body_zh"] if zh else story["body_en"],
    }
