"""Fun fictional retail investor stories shown to the player.

Each story is filed like an archival dossier: era, file number, record date,
source, and an atmospheric prologue, so the game reads like a small archive of
market folklore rather than plain jokes.
"""

STAMP = {"zh": "散户密档", "en": "RETAIL DOSSIER"}

STORIES = [
    {
        "id": "s01",
        "file_no": "DS-1993-001",
        "tag_zh": "听消息",
        "tag_en": "Hot tip",
        "era_zh": "1993 · 消息时代",
        "era_en": "1993 · The Age of Rumors",
        "date_zh": "1993 年 · 春",
        "date_en": "Spring 1993",
        "source_zh": "七大姑的牌友",
        "source_en": "Auntie's mahjong partner",
        "title_zh": "七大姑的独家内幕",
        "title_en": "Auntie's Insider Info",
        "prologue_zh": "那一年，上海街头的每个人，口袋里都揣着一本手抄的股票笔记。",
        "prologue_en": "That year, on the streets of Shanghai, everyone carried a handwritten stock notebook.",
        "body_zh": "老李的七大姑从牌友那里听说某股票要重组，他连夜满仓。第二天公司发公告说“近期无重大事项”，老李说：消息没错，是行情没听懂。",
        "body_en": "Li's aunt heard from a mahjong partner that a stock was about to restructure, so he went all in overnight. The next day the company announced \"no major events.\" Li says the tip was right, the market just didn't understand it.",
    },
    {
        "id": "s02",
        "file_no": "DS-2018-002",
        "tag_zh": "抄底",
        "tag_en": "Catching the knife",
        "era_zh": "2018 · 漫长的冬天",
        "era_en": "2018 · The Long Winter",
        "date_zh": "2018 年 · 冬",
        "date_en": "Winter 2018",
        "source_zh": "雪球评论区",
        "source_en": "a stock forum comment thread",
        "title_zh": "战略建仓",
        "title_en": "Strategic Positioning",
        "prologue_zh": "熊市的冬天比往年更长，有人说春天快来了，有人说春天已经走了。",
        "prologue_en": "The bear market winter dragged on longer than usual. Some said spring was coming; others said it had already left.",
        "body_zh": "小王坚信“跌多了就是送钱”，每跌 5% 加一次仓。连加十次后，他把这叫做“战略建仓”，而他的持仓成本线已经比海拔还高了。",
        "body_en": "Wang believes every drop is free money and adds shares after each 5% decline. After ten adds he calls it \"strategic positioning,\" and his average cost is now higher than Mount Everest.",
    },
    {
        "id": "s03",
        "file_no": "DS-2008-003",
        "tag_zh": "死扛",
        "tag_en": "Diamond hands",
        "era_zh": "2008 · 六千点到两千点",
        "era_en": "2008 · From 6,000 to 2,000",
        "date_zh": "2008 年 · 秋",
        "date_en": "Autumn 2008",
        "source_zh": "小区广场舞队口述",
        "source_en": "oral history from the square-dance group",
        "title_zh": "回本就走",
        "title_en": "Sell When I Break Even",
        "prologue_zh": "从六千点到两千点，只需要一年。从那以后，每个人都学会了一个词：套牢。",
        "prologue_en": "From 6,000 points to 2,000 points in a single year. From then on, everyone learned one word: trapped.",
        "body_zh": "张姐买了只股票套了三年，她的止损规则是“等回本就卖”。三年后股价真的回本了，她说：涨这么猛，先不卖了，等翻倍。",
        "body_en": "Zhang has held a stock underwater for three years; her stop-loss rule is \"sell when I break even.\" When the price finally recovered, she said it was climbing too fast to sell, so she would wait for it to double.",
    },
    {
        "id": "s04",
        "file_no": "DS-2007-004",
        "tag_zh": "卖飞",
        "tag_en": "Sold too soon",
        "era_zh": "2007 · 全民炒股",
        "era_en": "2007 · A Nation of Traders",
        "date_zh": "2007 年 · 夏",
        "date_en": "Summer 2007",
        "source_zh": "出租车电台",
        "source_en": "taxi radio",
        "title_zh": "我曾买过",
        "title_en": "I Used to Own It",
        "prologue_zh": "那一年，连出租车司机都在聊涨停，路边小店的电视机永远停在财经频道。",
        "prologue_en": "That year, even taxi drivers discussed limit-ups, and every corner shop TV stayed on the finance channel.",
        "body_zh": "刘叔买完第二天涨了 2% 就跑了，美滋滋。结果那只股票一年涨了 6 倍，现在“我曾经买过”这句话已经写进了他的家族史。",
        "body_en": "Uncle Liu sold after a 2% gain and felt great. The stock went up 6x that year, and \"I used to own it\" has since become part of his family history.",
    },
    {
        "id": "s05",
        "file_no": "DS-2015-005",
        "tag_zh": "杠杆",
        "tag_en": "Leverage",
        "era_zh": "2015 · 杠杆牛市",
        "era_en": "2015 · The Leverage Bull",
        "date_zh": "2015 年 · 春",
        "date_en": "Spring 2015",
        "source_zh": "朋友圈截图",
        "source_en": "a screenshot from a friend circle",
        "title_zh": "牛市靠胆量",
        "title_en": "Bull Markets Reward Courage",
        "prologue_zh": "那一年，杠杆把每个人的胆子都撑大了，也把每个人的账户都架在了火上。",
        "prologue_en": "That year, leverage inflated everyone's courage and propped every account over the fire.",
        "body_zh": "小赵开了 5 倍杠杆，一天赚了 15%，他兴奋地发朋友圈“牛市靠胆量”。第二天亏了 20%，他的朋友圈更新成了“市场有风险”。",
        "body_en": "Zhao used 5x leverage and made 15% in one day, posting \"bull markets reward courage.\" The next day he lost 20% and reposted: \"markets are risky.\"",
    },
    {
        "id": "s06",
        "file_no": "DS-2024-006",
        "tag_zh": "玄学",
        "tag_en": "Fortune telling",
        "era_zh": "2024 · 玄学时代",
        "era_en": "2024 · The Age of Mysticism",
        "date_zh": "2024 年 · 冬",
        "date_en": "Winter 2024",
        "source_zh": "炒股群玄学组",
        "source_en": "the mysticism channel of a trading group",
        "title_zh": "招财猫形态",
        "title_en": "The Lucky Cat Pattern",
        "prologue_zh": "那几年，K 线的意义早已超越技术分析，开始像卦象一样被郑重解读。",
        "prologue_en": "In those years, candlesticks outgrew technical analysis and were solemnly read like fortune sticks.",
        "body_zh": "陈叔选股不看财报，只看手机尾号和 K 线形状。他说那根 W 底长得像他家的招财猫，于是果断买进，并给它取名“招财底”。",
        "body_en": "Chen picks stocks by the last digits of his phone number and the shapes on his chart. He saw a W bottom that looked like his lucky cat, bought in, and named it the \"lucky cat pattern.\"",
    },
    {
        "id": "s07",
        "file_no": "DS-2007-007",
        "tag_zh": "电梯内幕",
        "tag_en": "Elevator insider",
        "era_zh": "2007 · 电梯里的牛市",
        "era_en": "2007 · The Elevator Bull",
        "date_zh": "2007 年 · 秋",
        "date_en": "Autumn 2007",
        "source_zh": "写字楼电梯",
        "source_en": "an office building elevator",
        "title_zh": "电梯里的两个西装男",
        "title_en": "Two Guys in Suits",
        "prologue_zh": "那一年，电梯里只有两种话题：房价，和股票。",
        "prologue_en": "That year, elevators had only two topics: housing, and stocks.",
        "body_zh": "小吴在电梯里听到两个西装男在聊某只股票，当场下单。后来才知道，那两个人是另一家公司的销售，在聊客户名字。",
        "body_en": "Wu bought a stock because he overheard two men in suits discussing it in the elevator. It turned out they were salesmen from another company, talking about a client's name.",
    },
    {
        "id": "s08",
        "file_no": "DS-2015-008",
        "tag_zh": "满仓",
        "tag_en": "All in",
        "era_zh": "2015 · 全民股神",
        "era_en": "2015 · Everyone a Stock God",
        "date_zh": "2015 年 · 夏",
        "date_en": "Summer 2015",
        "source_zh": "丈母娘语录",
        "source_en": "words of the mother-in-law",
        "title_zh": "全家总动员",
        "title_en": "Family Mobilization",
        "prologue_zh": "那一年，全民都是股神，没人记得风险长什么样。",
        "prologue_en": "That year, everyone was a stock god, and nobody remembered what risk looked like.",
        "body_zh": "老周把买菜钱、孩子压岁钱和备用金都转进了账户，称之为“全家总动员”。月底账户缩水，他称之为“全家福”。",
        "body_en": "Zhou moved the grocery money, the kids' red envelopes, and the emergency fund into trading, calling it \"family mobilization.\" When the account shrank at month end, he called it \"a family portrait.\"",
    },
    {
        "id": "s09",
        "file_no": "DS-2015-009",
        "tag_zh": "割肉",
        "tag_en": "Cut losses",
        "era_zh": "2015 · 千股跌停",
        "era_en": "2015 · A Thousand Limit-Downs",
        "date_zh": "2015 年 · 夏",
        "date_en": "Summer 2015",
        "source_zh": "证券公司营业部",
        "source_en": "a brokerage branch office",
        "title_zh": "我一卖它就涨",
        "title_en": "It Rallies the Moment I Sell",
        "prologue_zh": "那个夏天，千股跌停像一场集体噩梦，醒来后每个人都在互相安慰：这只是技术性调整。",
        "prologue_en": "That summer, a thousand stocks hit limit-down together like a shared nightmare, and everyone woke up reassuring each other: it's only a technical correction.",
        "body_zh": "小孙刚割完肉，股票立刻涨停。他总结出新规律：只要我卖，它必涨。现在他成了小区公认的反向指标。",
        "body_en": "Sun sold at a loss and the stock hit the daily limit instantly. He discovered a rule: whenever he sells, it rallies. He is now the neighborhood's official reverse indicator.",
    },
    {
        "id": "s10",
        "file_no": "DS-2008-010",
        "tag_zh": "回本",
        "tag_en": "Break even",
        "era_zh": "2008 · 等待回本",
        "era_en": "2008 · Waiting to Break Even",
        "date_zh": "2008 年 · 冬",
        "date_en": "Winter 2008",
        "source_zh": "散户聚会",
        "source_en": "a retail investor gathering",
        "title_zh": "再赚五万就收手",
        "title_en": "Fifty Thousand More and I Quit",
        "prologue_zh": "账户缩水一半的人，都在等同一个词：回本。",
        "prologue_en": "Everyone whose account had halved was waiting for the same word: break even.",
        "body_zh": "马姐的账户从 20 万亏到 8 万，她每天祈祷“回本就好”。等她真的回本那天，她决定“再赚 5 万就收手”，然后开始了新一轮祈祷。",
        "body_en": "Ma's account fell from 200k to 80k and she prayed daily just to break even. The day she finally did, she decided to \"make 50k more and quit,\" starting a whole new round of praying.",
    },
    {
        "id": "s11",
        "file_no": "DS-2015-011",
        "tag_zh": "借钱",
        "tag_en": "Borrowed money",
        "era_zh": "2015 · 勇气与杠杆",
        "era_en": "2015 · Courage and Leverage",
        "date_zh": "2015 年 · 春",
        "date_en": "Spring 2015",
        "source_zh": "亲戚饭局",
        "source_en": "a family dinner",
        "title_zh": "等风来",
        "title_en": "Waiting for the Wind",
        "prologue_zh": "那一年，借钱炒股不再被看作鲁莽，而被看作一种勇气。",
        "prologue_en": "That year, borrowing to trade was no longer seen as reckless, but as courage.",
        "body_zh": "小郑找亲戚借了 10 万“短期周转”，亲戚问多久，他说“等风来”。三个月后亲戚再问，他说“风还在路上”。",
        "body_en": "Zheng borrowed 100k from relatives for \"short-term liquidity.\" Asked how long, he said \"until the wind comes.\" Three months later they asked again; the wind was still on its way.",
    },
    {
        "id": "s12",
        "file_no": "DS-2018-012",
        "tag_zh": "装死",
        "tag_en": "Playing dead",
        "era_zh": "2018 · 账户体检",
        "era_en": "2018 · The Account Checkup",
        "date_zh": "2018 年 · 冬",
        "date_en": "Winter 2018",
        "source_zh": "深夜复盘者自述",
        "source_en": "a late-night chart-watcher's account",
        "title_zh": "我装作没买过",
        "title_en": "Pretending to Own Nothing",
        "prologue_zh": "那一年，打开炒股软件比打开体检报告更需要勇气。",
        "prologue_en": "That year, opening the trading app took more courage than opening a medical report.",
        "body_zh": "阿强被套后养成了新习惯：每天打开软件只看一眼就关，装作自己没买过。直到某天误触卖出键，他才想起自己还有持仓。",
        "body_en": "After getting trapped, Qiang got into the habit of opening his app, glancing at it, and closing it, pretending he owned nothing. One day he accidentally hit sell and remembered he had positions.",
    },
    {
        "id": "s13",
        "file_no": "DS-2021-013",
        "tag_zh": "直播炒股",
        "tag_en": "Live trading",
        "era_zh": "2021 · 直播间时代",
        "era_en": "2021 · The Livestream Era",
        "date_zh": "2021 年 · 秋",
        "date_en": "Autumn 2021",
        "source_zh": "直播间弹幕",
        "source_en": "livestream chat",
        "title_zh": "321 上车",
        "title_en": "3, 2, 1, Get In",
        "prologue_zh": "那几年，直播间里的“三、二、一”，比开盘钟声还要响亮。",
        "prologue_en": "In those years, the \"three, two, one\" in livestreams rang louder than the opening bell.",
        "body_zh": "小丽跟着某财经主播“321 上车”追了一只票，买完主播就下播了。她后来发现主播的简介写着：本节目仅供娱乐。",
        "body_en": "Li chased a stock with a streamer shouting \"3, 2, 1, get in!\", and the streamer went offline right after she bought. She later noticed the bio: \"For entertainment only.\"",
    },
    {
        "id": "s14",
        "file_no": "DS-2007-014",
        "tag_zh": "一夜暴富",
        "tag_en": "Get rich quick",
        "era_zh": "2007 · 十年大牛",
        "era_en": "2007 · The Ten-Year Bull",
        "date_zh": "2007 年 · 秋",
        "date_en": "Autumn 2007",
        "source_zh": "老年活动室",
        "source_en": "a senior activity room",
        "title_zh": "大不了重新上班",
        "title_en": "Worst Case, I Go Back to Work",
        "prologue_zh": "那一年，每个人都相信十年大牛刚刚开始，退休金只是起跑线。",
        "prologue_en": "That year, everyone believed the ten-year bull market had just begun, and a pension was just the starting line.",
        "body_zh": "老钱把退休金押进去赌“百年大行情”，他说“大不了重新上班”。后来他真的重新上班了，工牌上写着“夜班保安”。",
        "body_en": "Qian put his pension into a \"once-in-a-century rally,\" saying \"worst case, I go back to work.\" He did. His badge now reads \"night security guard.\"",
    },
    {
        "id": "s15",
        "file_no": "DS-2022-015",
        "tag_zh": "反向操作",
        "tag_en": "Contrarian",
        "era_zh": "2022 · 原地踏步的指数",
        "era_en": "2022 · The Index That Never Moved",
        "date_zh": "2022 年 · 夏",
        "date_en": "Summer 2022",
        "source_zh": "股吧热帖",
        "source_en": "a hot forum post",
        "title_zh": "负负得正",
        "title_en": "Two Negatives Make a Positive",
        "prologue_zh": "那一年，指数还在原地，交易的人已经换了好几茬。",
        "prologue_en": "That year, the index stayed put while the people trading it came and went several times over.",
        "body_zh": "小何发现自己看好的股票都跌、看不上的都涨，于是决定反着买。结果两只一起跌，他说：我这叫负负得正。",
        "body_en": "He noticed that stocks he liked fell and stocks he disliked rallied, so he bought the ones he disliked. Both fell together. His explanation: two negatives make a positive.",
    },
    {
        "id": "s16",
        "file_no": "DS-2019-016",
        "tag_zh": "情绪管理",
        "tag_en": "Emotional trading",
        "era_zh": "2019 · 白天复盘，夜里失眠",
        "era_en": "2019 · Charts by Day, Sleepless by Night",
        "date_zh": "2019 年 · 秋",
        "date_en": "Autumn 2019",
        "source_zh": "心理诊所病历",
        "source_en": "a clinic case file",
        "title_zh": "盘感依赖症",
        "title_en": "Chart Obsession Disorder",
        "prologue_zh": "那一年，白天复盘和夜里失眠，其实是同一件事。",
        "prologue_en": "That year, reviewing charts by day and lying awake at night were the same thing.",
        "body_zh": "老韩每次亏钱就喝酒，喝完就加仓，加完就后悔，后悔就睡不着，睡不着就再看盘。医生说他得了“盘感依赖症”。",
        "body_en": "Han drinks after every loss, adds shares after drinking, regrets it, can't sleep, and checks the charts again. His doctor calls it \"chart-obsession disorder.\"",
    },
    {
        "id": "s17",
        "file_no": "DS-2020-017",
        "tag_zh": "开盘前",
        "tag_en": "Before the bell",
        "era_zh": "2020 · 神圣的十分钟",
        "era_en": "2020 · The Sacred Ten Minutes",
        "date_zh": "2020 年 · 春",
        "date_en": "Spring 2020",
        "source_zh": "开盘前战歌歌单",
        "source_en": "a pre-open anthem playlist",
        "title_zh": "战歌选错了",
        "title_en": "Wrong Battle Anthems",
        "prologue_zh": "那一年，开盘前的十分钟，是一天中最神圣的时刻。",
        "prologue_en": "That year, the ten minutes before the open were the most sacred part of the day.",
        "body_zh": "小杨每天开盘前都要听三首战歌，说这样“气势如虹”。结果开盘十分钟账户就绿了，他说战歌选错了，明天换一首。",
        "body_en": "Yang plays three battle anthems before every open to \"boost morale.\" His account turns green within ten minutes, so he swears he picked the wrong songs and will swap them tomorrow.",
    },
    {
        "id": "s18",
        "file_no": "DS-2021-018",
        "tag_zh": "股神附体",
        "tag_en": "Stock god",
        "era_zh": "2021 · 人人都是巴菲特",
        "era_en": "2021 · Everyone a Buffett",
        "date_zh": "2021 年 · 夏",
        "date_en": "Summer 2021",
        "source_zh": "辞职信附录",
        "source_en": "an appendix to a resignation letter",
        "title_zh": "巴菲特转世",
        "title_en": "Reborn as Buffett",
        "prologue_zh": "那一年，每个人都觉得自己是下一个巴菲特，只是暂时还没人兑现。",
        "prologue_en": "That year, everyone believed they were the next Buffett; they just hadn't cashed in yet.",
        "body_zh": "阿杰连续三天猜对涨跌，觉得自己是巴菲特转世，宣布辞职专职炒股。第一周结束，他开始研究外卖骑手的入职流程。",
        "body_en": "Jay predicted three days of moves correctly, declared himself the reincarnation of Buffett, and quit his job to trade full time. By the end of week one he was researching delivery driver applications.",
    },
    {
        "id": "s19",
        "file_no": "DS-2015-019",
        "tag_zh": "股吧大师",
        "tag_en": "Forum guru",
        "era_zh": "2015 · 散户国会山",
        "era_en": "2015 · The Retail Parliament",
        "date_zh": "2015 年 · 夏",
        "date_en": "Summer 2015",
        "source_zh": "股吧删帖记录",
        "source_en": "deleted forum post records",
        "title_zh": "战术性撤退",
        "title_en": "A Tactical Retreat",
        "prologue_zh": "那一年，股吧就是散户的国会山，发帖的人比看盘的人还多。",
        "prologue_en": "That year, the stock forum was retail investors' parliament, with more posters than chart-watchers.",
        "body_zh": "老牛白天在群里发“耐心持有，价值投资”，晚上偷偷挂单割肉。群友发现后，他解释：这叫战术性撤退。",
        "body_en": "Niu preaches \"patience and value investing\" in the group chat by day, then quietly sells at a loss at night. When caught, he calls it a tactical retreat.",
    },
    {
        "id": "s20",
        "file_no": "DS-2019-020",
        "tag_zh": "目标价",
        "tag_en": "Target price",
        "era_zh": "2019 · 科创板元年",
        "era_en": "2019 · The STAR Market Year",
        "date_zh": "2019 年 · 夏",
        "date_en": "Summer 2019",
        "source_zh": "科创板开户柜台",
        "source_en": "the STAR Market account desk",
        "title_zh": "四舍五入再等等",
        "title_en": "Rounding Up",
        "prologue_zh": "那一年，科创板开市，新的故事开始了，新的目标价也是。",
        "prologue_en": "That year, the STAR Market opened, and with it came new stories and new target prices.",
        "body_zh": "小美买股票前设好目标价“赚 30% 就卖”。股票涨到 28% 时她犹豫了，四舍五入一下，决定再等等。后来她的目标价改成了“回本就走”。",
        "body_en": "Mei sets a 30% target before buying. At 28% she hesitates, rounds up, and waits a little longer. Her target eventually becomes \"sell when I break even.\"",
    },
]


def localize_story(story: dict, lang: str) -> dict:
    zh = lang == "zh"
    return {
        "id": story["id"],
        "file_no": story["file_no"],
        "tag": story["tag_zh"] if zh else story["tag_en"],
        "era": story["era_zh"] if zh else story["era_en"],
        "date": story["date_zh"] if zh else story["date_en"],
        "source": story["source_zh"] if zh else story["source_en"],
        "stamp": STAMP["zh" if zh else "en"],
        "title": story["title_zh"] if zh else story["title_en"],
        "prologue": story["prologue_zh"] if zh else story["prologue_en"],
        "story": story["body_zh"] if zh else story["body_en"],
    }
